version: '3'

services:
    backend:
        container_name: wany-backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - ./backend/.env
            - ./backend/.env.local
            - ./backend/.env.production
        depends_on:
            database:
                condition: service_healthy

    frontend:
        container_name: wany-frontend
        image: nginx:latest
        ports:
            - '8080:8080'
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - backend

    database:
        image: mysql:8.0.34
        environment:
            MYSQL_DATABASE: 'wany'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3308:3306'
        volumes:
            - database:/var/lib/mysql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10

volumes:
    database:
