version: '3'

services:
    api:
        container_name: wany-api
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - ./backend/.env
            - ./backend/.env.local
            - ./backend/.env.production
        depends_on:
            - db

    client:
        container_name: wany-static
        image: nginx:latest
        ports:
            - '8080:8080'
        volumes:
            - ./frontend:/var/www/html
            - ./nginx.conf:/etc/nginx/nginx.conf

    db:
        image: mysql:8.0.34
        environment:
            MYSQL_DATABASE: 'wany'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3308:3306'
        volumes:
            - db:/var/lib/mysql

volumes:
    db:
